---
# defaults file for common
common_packages_redhat:
  - vim
  - "@Development Tools"
  - net-tools
  - nmap
  - tcpdump
  - wget
  - screen
  - unzip

common_packages_debian:
  - vim
  - build-essential
  - net-tools
  - nmap
  - tcpdump
  - wget
  - screen
  - python
...
